### ISSUE TITLE
[Request] Custom item groups using tag system

### ISSUE THREAD

**Issue by Bazyliii** [KessokuTeaTime/REI-Collapsible-Entries#2]
Hey, just like in the title is there a possibility that you would make that feature? Like simple config file where for example I could add tag like: **c:workbenches** and your mod will automatically make group with name **Collapsed Entry: Workbenches**.

I think that this is doable :) Anyway keep up good work!

**Comment by KrLite** [comment]
Yeah, that will be quite a useful feature. I will try to implement that to enable more flexibility. Thanks for advising!

**Comment by KrLite** [comment]
I'm currently planning for:

- [X] A `TOML` array config storing custom tags.
- [X] A ~robust~ config page powered by auto config where players can check and add custom tags in-game.
- [X] Some useful commands for players to get hand held item's tags conveniently.

**Comment by KrLite** [comment]
Currently it has naming issues, but it worked. 🎉
(this is tag `minecraft:piglin_repellents`)
<img width="966" alt="image" src="https://github.com/KrLite/Mod.REI-Collapsible-Entries-QOL/assets/68179735/c75a10f8-1c5d-404d-93f6-3e54027cfeb7">

**Comment by Bazyliii** [comment]
Looks good man :D

**Comment by KrLite** [comment]
Now if you use command `/reicollapsibleentries tags` while holding an item, all of its tags will be printed to the chat and by clicking one of them you can toggle the custom tags directly.
<img width="966" alt="image" src="https://github.com/KrLite/Mod.REI-Collapsible-Entries-QOL/assets/68179735/d714aa5d-59dd-43c1-80db-ff465f14498f">
And the actual entry looks like:
<img width="966" alt="image" src="https://github.com/KrLite/Mod.REI-Collapsible-Entries-QOL/assets/68179735/3c769224-4800-4a9a-85af-cb9e4aa356a8">
It is available in the upcoming release.

**Comment by TheSnowyChickens** [comment]
Hi, I found a crash while using the ingame command feature.

I hold some dirt in my hand, used the command and clicked on the tag in the chat and after a freeze, it crashed.

-> 
[crash-2024-02-28_16.45.30-client.txt](https://github.com/KrLite/Mod.REI-Collapsible-Entries-QOL/files/14436505/crash-2024-02-28_16.45.30-client.txt)


I have only installed REI / Your mod / Architectury / Fabric API and Cloth Config on 1.20.4 with Fabric 1.15.7 (everything new downloaded)

-----

But that is not the reason for my post (it was just an extra), could you maybe add a little example in your config file, how we can add a new tag and how to format ? (like with "" and , )

Ty

(collapsible entries are very useful and via REI changelog from version 8.3 (or something like that), they are integrated in REI, but I have no clue how to use them, your mod was the only possible solution for me)

**Comment by KrLite** [comment]
### For the Crash:

It is OK on `1.20`, and in your case it is caused by illegally accessing a private field. I suspect that Minecraft `1.20.2+` had made some changes in the fields of the screens the mod uses, causing the access to be no more legal. However, I don't want to maintain another branch just for the fix. I will find another solution for this.

It won't take up too much time.

### For the Config:

Well, as the library I use (basically toml4j) doesn't provide a way to programmatically add comments to config files, so it's not possible to provide commented examples. However, I may include some of them in an updated description.

**It's easy for anyone who has had experiences with basic data structures. I hereby explain it for you:**

This is an empty array with a key, in key-value config structures:

```toml
key = []
```

You shouldn't modify the key and the `=` sign, but all the whitespaces and new lines will be ignored.

**Let us have a look at the value, in this case, the array.**

In the brackets you can add elements separated by ENGLISH `,` and unlimited optional whitespaces or new lines. A possible structure under this syntax is:

```toml
key = [element, element,
element
]
```

To be more specific, we use strings as elements, that are, tags quoted by pairs of ENGLISH `"`.

The tag follows the basic structure of Minecraft identifiers, that is, `namespace`, followed by `:`, followed by `path`. For example, `minecraft:ores` and `c:ores` (these tags are made up).

So the final result might be:

```toml
key = [
  "c:tag_1", 
  "minecraft:tag_2", 
  "a:b"
]
```

I hope this one helps you understand how the array config works.

**Comment by Bazyliii** [comment]
Looks just like I thought it will 🤩

**Comment by TheSnowyChickens** [comment]
Okay, no clicking on chat messages for now. :D 

That was a very detailed explanation, good job and thank you. ❤️ 

Time to clean up REI in my pack^^

**Comment by KrLite** [comment]
The crash turns out to be that I forgot to add the access widener path into my `fabric.mod.json`.

**Comment by KrLite** [comment]
It's here: https://modrinth.com/mod/rei-collapsible-entries/version/3.0.1-mc1.20

**Comment by TheSnowyChickens** [comment]
Ty 🙏
